# Generated by Django 6.0.5 on 2026-05-25 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 — Direct Emissions'), (2, 'Scope 2 — Indirect (Electricity)'), (3, 'Scope 3 — Value Chain')])),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP — Fuel'), ('SAP_PROC', 'SAP — Procurement'), ('UTILITY_ELEC', 'Utility — Electricity'), ('TRAVEL_FLIGHT', 'Travel — Flight'), ('TRAVEL_HOTEL', 'Travel — Hotel')], max_length=20)),
                ('activity_date', models.DateField()),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('L', 'Liters'), ('kWh', 'Kilowatt-hours'), ('pass-km', 'Passenger-kilometres'), ('nights', 'Hotel Nights'), ('kg', 'Kilograms')], max_length=20)),
                ('emission_factor', models.FloatField(help_text='kgCO2e per unit')),
                ('co2e_kg', models.FloatField(help_text='Total kgCO2e = quantity × emission_factor')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked')], default='PENDING', max_length=20)),
                ('flag_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('EDIT', 'Field Edited'), ('FLAG', 'Record Flagged'), ('APPROVE', 'Record Approved'), ('LOCK', 'Record Locked'), ('CREATE', 'Record Created')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='esg.activityrecord')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SAP', 'SAP Fuel/Procurement'), ('UTILITY', 'Utility Portal'), ('TRAVEL', 'Corporate Travel API')], max_length=20)),
                ('scope', models.IntegerField(blank=True, choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')], null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial (with errors)')], default='PENDING', max_length=20)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='ingestions/')),
                ('record_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='esg.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='esg.organization'),
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20)),
                ('raw_json', models.JSONField()),
                ('row_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='esg.ingestionlog')),
            ],
            options={
                'ordering': ['ingestion_log', 'row_index'],
            },
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_record', to='esg.rawrecord'),
        ),
    ]
